# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1



- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'sonarCloud'
    organization: 'anubhavdev-organization'
    scannerMode: 'MSBuild'
    projectKey: 'Anubhav'
    projectName: 'Projectfor.net'

- task: SonarCloudAnalyze@2

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'

