trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Setup
  jobs:
  - job: InstallTools
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '4.8'

- stage: Build
  jobs:
  - job: BuildProject
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
        
- stage: QualityAnalysis
  jobs:
  - job: PrepareSonarCloudAnalysis
    steps:
    - task: SonarCloudPrepare@2
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'anubhavbhardwaj9759'
        scannerMode: 'MSBuild'
        projectKey: '9216332bb16d2a7d503056f7d539f3f0501c982b'
        projectName: 'DotNet Project'

  - job: AnalyzeWithSonarCloud
    dependsOn: PrepareSonarCloudAnalysis
    steps:
    - task: SonarCloudAnalyze@2
      inputs:
        jdkversion: 'JAVA_HOME'

  - job: PublishSonarCloudReport
    dependsOn: AnalyzeWithSonarCloud
    steps:
    - task: SonarCloudPublish@2
      inputs:
        pollingTimeoutSec: '300'
