trigger:
- main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Setup
  jobs:
  - job: InstallTools
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '6.10.1'

- stage: Build
  jobs:
  - job: BuildProject
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

- stage: QualityAnalysis
  jobs:
  - job: PrepareSonarCloudAnalysis
    steps:
    - task: SonarCloudPrepare@2
      inputs:
        SonarCloud: 'sonarCloud'
        organization: 'anubhavdev-organization'
        scannerMode: 'MSBuild'
        projectKey: 'Anubhav'
        projectName: 'Projectfor.net'

  - job: AnalyzeWithSonarCloud
    dependsOn: PrepareSonarCloudAnalysis
    steps:
    - task: SonarCloudAnalyze@2

  - job: PublishSonarCloudReport
    dependsOn: AnalyzeWithSonarCloud
    steps:
    - task: SonarCloudPublish@2
      inputs:
        pollingTimeoutSec: '300'
